---
version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo:5.0.6
    ports:
      - '27017:27017'
    command: --replSet rs0

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'